### ISSUE TITLE
"The connection was reset" on fpm images

### ISSUE THREAD

**Issue by SethFalco** [joomla-docker/docker-joomla#119]
I was trying to set up Joomla locally, however ran into some issues.

The following are inaccessible on first launch due:
* 3.9.26-php7.4-fpm-alpine
* 3.9.26-php7.4-fpm ([Logs](https://gist.github.com/SethFalco/42afed7fda0d6830f8054de6dbae4af4))

Firefox displays the error: "The connection was reset".

The following work perfectly fine on first launch:
* 3.9.26-apache
* 3.9.26-php7.4-apache ([Logs](https://gist.github.com/SethFalco/131dfe16ffaf947eadfcc5e11e763927))

The logs attached are for the same configuration. It only consists of initializing a fresh instance and attempting to access it in the browser.

```yml
version: '3.1'

services:
  joomla:
    image: joomla:3.9.26-{...}
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
      - "../:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: {REDACTED}

  joomladb:
    image: mysql:5.6
    ports:
      - 3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: {REDACTED}
```

Not entirely sure what's wrong here, but I'm on standby to do any further testing and provide additional information.
