### ISSUE TITLE
Upgrade of Joomla from 3.x to 4.x Media Functions do not work

### ISSUE THREAD

**Issue by MelbosaRW** [joomla-docker/docker-joomla#138]
I upgraded a docker install of Joomla from 3.x to 4.x within the application, and then updated docker php-fpm version to a newer image (tested both 7.4 & 8.0 tested). 

NOTE: Prior to upgrade, this functionality was working fine.

Image Tag Used: `joomla:php8.0-fpm-alpine`

Within Joomla 4.1.0 when using docker image, if you go to Content > Media, the page loads fine, and I can navigate through exiting folders/files just fine.  But I am unable to:

* Create a Folder - Which results in generic: Error creating folder
* Upload Files - Dialog pops up, select file, then closes no error

Logs show these errors: 
```
joomla-php-fpm_1  | 172.18.0.4 -  16/Feb/2022:21:36:13 +0000 "POST /administrator/index.php" 500

joomla-php-fpm_1  | NOTICE: PHP message: PHP Warning:  iconv(): Wrong encoding, conversion from &quot;UTF-8&quot; to &quot;ASCII//TRANSLIT//IGNORE&quot; is not allowed in /var/www/html/libraries/src/Filesystem/File.php on line 95

joomla-nginx_1    | 2022/02/16 21:36:13 [error] 31#31: *69 FastCGI sent in stderr: "PHP message: PHP Warning:  iconv(): Wrong encoding, conversion from &quot;UTF-8&quot; to &quot;ASCII//TRANSLIT//IGNORE&quot; is not allowed in /var/www/html/libraries/src/Filesystem/File.php on line 95" while reading response header from upstream, client: 172.19.0.4, server: www.rwoc.ca, request: "POST /administrator/index.php?option=com_media&format=json&mediatypes=0,1,2,3&task=api.files&path=local-images:/ HTTP/1.1", upstream: "fastcgi://172.18.0.6:9000", host: "www.rwoc.ca", referrer: "https://www.rwoc.ca/administrator/index.php?option=com_media&path=local-images:/"

joomla-nginx_1    | 172.19.0.4 - - [16/Feb/2022:21:36:13 +0000] "POST /administrator/index.php?option=com_media&format=json&mediatypes=0,1,2,3&task=api.files&path=local-images:/ HTTP/1.1" 500 422 "https://www.rwoc.ca/administrator/index.php?option=com_media&path=local-images:/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "192.197.128.19"
```
Researching error indicates iconv php module may be missing in image, but from what I can see the modules needed are loaded.

The line of Code that throws the error is:
```
// Using iconv to ignore characters that can't be transliterated

$file = iconv("UTF-8", "ASCII//TRANSLIT//IGNORE", transliterator_transliterate('Any-Latin; Latin-ASCII', $file));
```

I should point out I have tested this upgrade on two 3.x to 4.x and same result.

**Comment by MelbosaRW** [comment]
You can review the PHP Information here: [https://www.rwoc.ca/phpinfo.php](https://www.rwoc.ca/phpinfo.php) (NOTE: this file is only temporarily enabled)

**Comment by JoMandalor** [comment]
This looks like a Joomla/PHP issue and not docker related. This file: /var/www/html/libraries/src/Filesystem/File.php on line 95 [changed two](https://github.com/joomla/joomla-cms/blame/49c1e96a77e192ab5cd1071df88ba2e48683218e/libraries/src/Filesystem/File.php#L95) months ago.

**Comment by MelbosaRW** [comment]
> This looks like a Joomla/PHP issue and not docker related. This file: /var/www/html/libraries/src/Filesystem/File.php on line 95 [changed two](https://github.com/joomla/joomla-cms/blame/49c1e96a77e192ab5cd1071df88ba2e48683218e/libraries/src/Filesystem/File.php#L95) months ago.
> 
> How long ago did you update your site?

I updated just this week.  It does appear to use the iconv module, but while it shows enabled in PHP Info, it also DOES NOT show in the loaded Configure Command on PHP Info:

`'./configure' '--build=x86_64-linux-musl' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-openssl' '--with-readline' '--with-zlib' '--with-pear' '--disable-cgi' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' 'build_alias=x86_64-linux-musl'`

Wondering if it is missing from the docker side?  Something like:

`--with-iconv`

**Comment by JoMandalor** [comment]
The iconv function seems to exits because:
```
if (function_exists('transliterator_transliterate') && function_exists('iconv'))
```
Means that if its not there it will not try to use it, the fact that it return true on both those means its there alright.

**Comment by MelbosaRW** [comment]
> The [iconv function seems to exits](https://github.com/joomla/joomla-cms/blob/49c1e96a77e192ab5cd1071df88ba2e48683218e/libraries/src/Filesystem/File.php#L92) because:
> 
> ```
> if (function_exists('transliterator_transliterate') && function_exists('iconv'))
> ```
> 
> Means that if its not there it will not try to use it, the fact that it return true on both those means its there alright.

So then, why this error?  Do I have to raise the issue on the Joomla GitHub?  I have people not running this in a docker and it does work.

**Comment by JoMandalor** [comment]
I just ran a few tests and it seems like the size limitation is not being handled correctly, and gives an error in the console but nothing in the browser (foxfire). But I could create folders upload images (below the size limit) and that with both php8.0 and php8.1 of Joomla 4.1

Did you check the image size limit?

**Comment by MelbosaRW** [comment]
Yes, I have overrides for that.  I am going to try a fresh install and see if I can just copy over the files to get it to work.

**Comment by MelbosaRW** [comment]
I did a fresh container, with fresh files and fresh install.  Still get the error:

```
test-joomla-php-fpm_1  | 172.18.0.7 -  17/Feb/2022:00:23:47 +0000 "POST /administrator/index.php" 500
test-joomla-php-fpm_1  | NOTICE: PHP message: PHP Warning:  iconv(): Wrong encoding, conversion from &quot;UTF-8&quot; to &quot;ASCII//TRANSLIT//IGNORE&quot; is not allowed in /var/www/html/libraries/src/Filesystem/File.php on line 95
test-joomla-nginx_1    | 2022/02/17 00:23:47 [error] 31#31: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  iconv(): Wrong encoding, conversion from &quot;UTF-8&quot; to &quot;ASCII//TRANSLIT//IGNORE&quot; is not allowed in /var/www/html/libraries/src/Filesystem/File.php on line 95" while reading response header from upstream, client: 172.19.0.3, server: test.rwoc.ca, request: "POST /administrator/index.php?option=com_media&format=json&mediatypes=0,1,2,3&task=api.files&path=local-images:/ HTTP/1.1", upstream: "fastcgi://172.18.0.6:9000", host: "test.rwoc.ca", referrer: "https://test.rwoc.ca/administrator/index.php?option=com_media&path=local-images:/"
test-joomla-nginx_1    | 172.19.0.3 - - [17/Feb/2022:00:23:47 +0000] "POST /administrator/index.php?option=com_media&format=json&mediatypes=0,1,2,3&task=api.files&path=local-images:/ HTTP/1.1" 500 422 "https://test.rwoc.ca/administrator/index.php?option=com_media&path=local-images:/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "192.197.128.19"
```

Here is my docker-compose.yml, which can be critiqued as needed:

```
version: '3.7'

services:
  test-joomla-nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./html:/var/www/html"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    environment:
      VIRTUAL_HOST: test.rwoc.ca
      LETSENCRYPT_HOST: test.rwoc.ca
      LETSENCRYPT_EMAIL: support@servuit.com
    networks:
      - default
      - db

  test-joomla-php-fpm:
    image: joomla:php8.0-fpm-alpine
    restart: always
    volumes:
      - "./html:/var/www/html"
      - "./php-fpm/conf.d/joomlphpoverides.ini:/usr/local/etc/php/conf.d/joomlphpoverides.ini"
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: joomlausr
      JOOMLA_DB_PASSWORD: "*******************"
      JOOMLA_DB_NAME: joomlatest
    networks:
      - default
      - db

networks:
  default:
    external:
      name: websites
  db:
    external:
      name: dbnet

```

If @JoMandalor you have this working, then I am not sure what I am doing wrong.
