### ISSUE TITLE
Update stack/compose example to remove restart and links

### ISSUE THREAD

**Issue by BretFisher** [joomla-docker/docker-joomla#41]
The README example of a stack.yml file could use updating to remove legacy/confusing options:

1. Links are no [longer needed as of compose v2](https://docs.docker.com/compose/compose-file/compose-file-v2/#links). Since this example uses v3.1, links should be removed.
2. `restart:` option [is only used for docker-compose](https://docs.docker.com/compose/compose-file/#restart), while `restart_policy:` is [only used for stack deploy](https://docs.docker.com/compose/compose-file/#restart_policy). Since it's an option setting, I'd recommend removing it from the example to avoid confusion [like this question on SO](https://stackoverflow.com/q/48111049/749924).

I can submit a PR (just let me know if you agree with above and I'll submit) or someone can just update the README to read:

```
version: '3.1'

services:
  joomla:
    image: joomla
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: example
```
